### ISSUE TITLE
websocket推送过来的实时数据，怎么更新到图表上

### ISSUE THREAD

**Issue by H-Sven** [zhengquantao/vue-Kline#1]
请问 websocket推送过来的实时数据，怎么更新到图表上

**Comment by zhengquantao** [comment]
把请求回来的数据重新赋值到this.klineData&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Demo_Hu"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 下午4:20
收件人: "zhengquantao/vue-Kline"<vue-Kline@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [zhengquantao/vue-Kline] websocket推送过来的实时数据，怎么更新到图表上 (#1)




请问 websocket推送过来的实时数据，怎么更新到图表上
 
&mdash;

**Comment by zhengquantao** [comment]
如果你看不懂github上的demo &nbsp; 可以加加github下面的那个群会有人告诉你咋弄




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Demo_Hu"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 下午4:20
收件人: "zhengquantao/vue-Kline"<vue-Kline@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [zhengquantao/vue-Kline] websocket推送过来的实时数据，怎么更新到图表上 (#1)




请问 websocket推送过来的实时数据，怎么更新到图表上
 
&mdash;

**Comment by zhengquantao** [comment]
> 请问websocket推送过来的实时数据，怎么更新到图表上

你需要把返回的数据重新赋值到this.klineData . 如果还不明白可以加一下下面的群
