### ISSUE TITLE
您好，点击ranges的事件，能详细说一下吗？怎么用？

### ISSUE THREAD

**Issue by csf0857** [zhengquantao/vue-Kline#13]
您好，点击ranges的事件，能详细说一下吗？怎么用？

**Comment by zhengquantao** [comment]
当你点击ranges的事件 会触发methods里面的 refreshKlineData这个方法,参数option 就是对应点击的回调时间（ms）, 你在这个方法里写判断是哪个时间"1w", "1d", "1h", "30m", "15m", "5m", "1m"。重新去请求对应的时间数据

**Comment by csf0857** [comment]
您好，我是新手，您这样说我还是不太了解具体的使用，我用不是VUE的，想通过ranges点击实现调用不同的接口，方便的话能给点代码指导吗？

**Comment by zhengquantao** [comment]
如果是HTML
![N_I9_`MQ8)FD {Y$7N6N_9V](https://user-images.githubusercontent.com/44289484/92318135-60bd2780-f03a-11ea-809c-30662f2a9d88.png)

**Comment by csf0857** [comment]
非常感谢您的指导，还有个问题就是数据显示不同步，html这边要怎么解决，打包下来的js里有那个updateDataAndDisplay方法，但是怎么用呢，用到kline的lines那边

**Comment by csf0857** [comment]
方便加个QQ吗？我直接QQ上问您

**Comment by zhengquantao** [comment]
加QQ就不要了 如果html你不同步你可以这样写  
![image](https://user-images.githubusercontent.com/44289484/92491603-ff0ce100-f224-11ea-90db-8a77fcaf7384.png)

**Comment by csf0857** [comment]
问题已经解决了，感谢大佬
