### ISSUE TITLE
vue-kline-demo 和 vue-kline 有什么区别嘛

### ISSUE THREAD

**Issue by wj85203** [zhengquantao/vue-Kline#21]
vue-kline-demo 和 vue-kline 有什么区别嘛

**Comment by wj85203** [comment]
怎么才能和大佬取得联系呀

**Comment by wj85203** [comment]
![QSB3JE~7H%@H`M7GL11}L6T](https://user-images.githubusercontent.com/72512003/116391087-519d1b00-a851-11eb-94f0-154547fba631.png)

**Comment by wj85203** [comment]
代码报错是什么原因呀

**Comment by zhengquantao** [comment]
不好意思  没有及时回复你的消息。这个报错的原因是pycharm编辑器不支持这样的操作。这个操作在vue中是可以的，你可以忽略这个error。
