### ISSUE TITLE
手机端点击图标报错

### ISSUE THREAD

**Issue by xianzhaoli** [zhengquantao/vue-kline#33]
![image](https://user-images.githubusercontent.com/32784906/157249658-82b15932-d0af-4eea-ad5f-807bb339826f.png)
![image](https://user-images.githubusercontent.com/32784906/157249691-7768ca06-ec15-423c-b379-2fa8f150e2cd.png)
@zhengquantao

**Comment by zhengquantao** [comment]
你的手机是哪个型号的呢

**Comment by zhengquantao** [comment]
> ![image](https://user-images.githubusercontent.com/32784906/157249658-82b15932-d0af-4eea-ad5f-807bb339826f.png) ![image](https://user-images.githubusercontent.com/32784906/157249691-7768ca06-ec15-423c-b379-2fa8f150e2cd.png) @zhengquantao

你的手机是哪个型号的呢

**Comment by zhengquantao** [comment]
应该是浏览器把这个方法更新了， 我适配一下
