### ISSUE TITLE
代码跑起来报错

### ISSUE THREAD

**Issue by zhoujun19930703** [zhengquantao/vue-Kline#5]
* ./css/main.css in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/kline/kline.vue  ,这个错误怎么改都改不掉，我用的vue-cli2，麻烦大神指教一下

**Comment by zhoujun19930703** [comment]
大佬，群在哪呢,没看见

**Comment by zhengquantao** [comment]
QQ群号(: 756319143)

**Comment by zhoujun19930703** [comment]
已申请，麻烦大佬通过一下

**Comment by hohband** [comment]
这个问题我也碰到了，怎么解决呢？

**Comment by zhengquantao** [comment]
这个项目是不能直接clone下来跑的呢  你需要自己新建一个vue项目在引入vue-kline才不会报错
